### ISSUE TITLE
Play with robobun + cherry

### ISSUE THREAD

**Issue by borkdude** [squint-cljs/cherry#82]
First time didn't work due to missing version

**Comment by robobun** [comment]
@borkdude here you go!
```tsx
1 | import { compileString } from 'cherry-cljs';
                                  ^
PackageVersionNotFound: No matching version found '>=0.0.0' for package 'cherry-cljs' (but package exists)
 pkg: "cherry-cljs"
      at /tmp/bun-Gma5Cp/index.js:2:31
```
<details>
  <summary>Code</summary>
  
```tsx
import { compileString } from 'cherry-cljs';
import { writeFileSync } from 'fs';

const code = compileString(`

(defn foo [^:js {:keys [x]}] x)

`);

writeFileSync('out.js', code);

const fooModule = await import('./out.js');

console.log(fooModule.foo({x: "Hello world!"}));
```
</details>

_Ran using the latest build of Bun, an all-in-one JavaScript runtime._

**Comment by robobun** [comment]
@borkdude here you go!
```tsx
1 | import { compileString } from 'cherry-cljs@0.0.0-alpha.60';
3 |
                 ^
TypeError: compileString is not a function. (In 'compileString(`
      at /tmp/bun-JVPOeM/index.js:4:13
```
<details>
  <summary>Code</summary>
  
```tsx
import { compileString } from 'cherry-cljs@0.0.0-alpha.60';
import { writeFileSync } from 'fs';

const code = compileString(`

(defn foo [^:js {:keys [x]}] x)

`);

writeFileSync('out.js', code);

const fooModule = await import('./out.js');

console.log(fooModule.foo({x: "Hello world!"}));
```
</details>

_Ran using the latest build of Bun, an all-in-one JavaScript runtime._

**Comment by borkdude** [comment]
@robobun

``` javascript
import { compileString } from 'cherry-cljs@0.0.0-alpha.60';
import { writeFileSync } from 'fs';

const code = compileString(`

(defn foo [^:js {:keys [x]}] x)

`);

writeFileSync('out.js', code);

const fooModule = await import('./out.js');

console.log(fooModule.foo({x: "Hello world!"}));
```
